name:
  - "Wordpress debug log"
url:
  - "/wp-content/debug.log"
method:
  - "GET"
data:
  - ""
matchers:
  - Status:
      - 200
  - Regex:
      - "[[0-9]{2}-[a-zA-Z]{3}-[0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2} [A-Z]{3}] PHP"