name:
  - "phpMyAdmin Panel"
url:
  - "/phpmyadmin/"
  - "/admin//phpmyadmin/"
  - "/_phpmyadmin/"
  - "/administrator/components/com_joommyadmin/phpmyadmin/"
  - "/phpMyAdmin"
  - "/forum/phpmyadmin/"
method:
  - "GET"
data:
  - ""
matchers:
  - Status:
      - 200
  - Regex:
      - "<title>phpMyAdmin"