name:
  - "Couchbase Buckets REST API - Unauthenticated"
url:
  - "/pools/default/buckets"
method:
  - "GET"
data:
  - ''
matchers:
  - Status:
      - 200
  - Regex:
      - '"couchbase":'