name:
  - "Laravel .env file accessible"
url:
  - "/.env"
  - "/.env.dev.local"
  - "/.env.development.local"
  - "/api/.env"
  - "/.env.local"
  - "/.env.example"
method:
  - "GET"
data:
  - ""
matchers:
  - Status:
      - 200
  - Regex:
      - "(?m)^APP_(NAME|ENV|KEY|DEBUG|URL|PASSWORD)="