name:
  - "Compro Technology IP Camera - ' mjpegStreamer.cgi' Screenshot Disclosure"
url:
  - "/mjpegStreamer.cgi"
method:
  - "GET"
data:
  - ""
matchers:
  - Status:
      - 200
  - Regex:
      - ""